#!/bin/bash
HERE="$(cd "$(dirname "$0")" && pwd)"
export APPDIR="$HERE"
export LD_LIBRARY_PATH="$HERE/usr/lib:$LD_LIBRARY_PATH"
export QML2_IMPORT_PATH="$HERE/usr/qml:$QML2_IMPORT_PATH"
export QML_IMPORT_PATH="$HERE/usr/qml:$QML_IMPORT_PATH"
exec "$HERE/usr/bin/DoomRunnerSD" "$@"
